name: Prisma PoC
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Installing dependencies
        run: yarn install

      - name: Listing files (ls -l)
        run: ls -l

      - name: Building app
        run: yarn build

      - name: List size
        run: du -hs build
